### ISSUE TITLE
Document should target master branch

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/tellurium#277]
Currently, Tellurium document targets develop branch for updates. This should be changed to master branch.

**Comment by 0u812** [comment]
Done

**Comment by kirichoi** [comment]
Thanks :+1:

**Comment by kirichoi** [comment]
This is actually not fixed. What I am talking about is the target for the 'latest' version. It is set to develop, not master. You can see this on the [document project page](https://readthedocs.org/projects/tellurium/) .

**Comment by kirichoi** [comment]
This needs to be fixed through readthedocs website, I believe.

**Comment by 0u812** [comment]
Oh I see. Should be fixed.

**Comment by kirichoi** [comment]
:+1: :+1: :+1:

**Comment by kirichoi** [comment]
Doc targets `2.0.x` branch right now. Please change it back to `master`.

**Comment by kirichoi** [comment]
Can someone add me to the project? You should be able to find me through `kirichoi`.

**Comment by matthiaskoenig** [comment]
@kirichoi I just added you as maintainer.

**Comment by 0u812** [comment]
readthedocs should target the 2.0.x branch because that is the branch that is currently released. I can merge it into master if desired, but I was holding off because that would make it more difficult to merge develop at some point.

**Comment by 0u812** [comment]
See also #280

**Comment by kirichoi** [comment]
Creating new branches for release is fine, but I honestly don't see the point. If this is temporary setup for paper submission, sure, but everything should be merged back into develop and master branch. These 2.0.x branches should be for nothing more than releases, and should simply branched off from develop or master branch at the time of release. In that case, creating 2.0.x branches provides no benefit over simply releasing on the master branch and targeting it for documents, etc.

From now on, I will push all my commits to develop branch. Once we decide to release a new version, we should simply PR to the master branch, so that master branch will only feature the latest stable release. 

For now, I will change the documentation build target back to 2.0.x
